### ISSUE TITLE
Issue with zlib on version 1.4.0

### ISSUE THREAD

**Issue by colinbrislawn** [torognes/vsearch#123]
Hello @torognes,

I've just downloaded `vsearch-1.4.0-linux-x86_64` and encountered this error.
`vsearch: /lib64/libz.so.1: version 'ZLIB_1.2.3.5' not found (required by vsearch)`

I'm a little surprised to find this because I'm using RHEL 6 and have zlib installed.
```
$ rpm -qa | grep zlib
zlib-1.2.3-29.el6.i686
zlib-1.2.3-29.el6.x86_64
zlib-devel-1.2.3-29.el6.x86_64
```

Would building vsearch from source fix this issue?

**Comment by colinbrislawn** [comment]
Building from source did indeed fix this issue.

**Comment by torognes** [comment]
hi @colinbrislawn 

Yes, building from source helps, but there is still something odd with it. I had to install a new version of zlib in a private folder, even though zlib is installed on the system. However, vsearch requires zlib version 1.2.4 or later. Version 1.2.3 (which I think is standard on RHEL 6) will not work properly, that is probably why we get the error message. Version 1.2.3 and earlier lacks the gzoffset function that we need.

Compiling from source will probably skip support for gzipped files as the correct version of the library is not available.

If you install zlib 1.2.4 or later you will probably be able to use the supplied binary or compile from source with gzip support.

We might need to provide alternative binaries. Maybe we can link the libraries statically.

**Comment by colinbrislawn** [comment]
You are correct; building from source works, but `gz` files are not supported. 

How should I go about building vsearch with the newest version of zlib?

**Comment by torognes** [comment]
If you install a new version of zlib on your system and rerun configure, it should be detected. When you run make after that, support for gzip compressed files should be included.

Note that zlib must be installed in the system folders (e.g. /lib). If it is installed elsewhere, make sure CPATH and LD_LIBRARY_PATH includes the path to where the zlib.h and the libz library, respectively, can be found.

**Comment by colinbrislawn** [comment]
Ah! zlib is not in my system path. 

When you say 'the libz library' do you mean these files?
```
lrwxrwxrwx  1 asdf users   13 Sep 25 14:18 libz.so -> libz.so.1.2.8*
lrwxrwxrwx  1 asdf users   13 Sep 25 14:18 libz.so.1 -> libz.so.1.2.8*
-rwxr-xr-x  1 asdf users  97K Sep 25 14:18 libz.so.1.2.8*
```

**Comment by torognes** [comment]
Yes, its those files that make the library. They are accompanied by a zlib.h header file, usually in the /include folder.

When you run configure you should see these lines if everything is okay:

...
checking for library containing BZ2_bzRead... -lbz2
checking for library containing gzoffset... -lz
...
checking bzlib.h usability... yes
checking bzlib.h presence... yes
checking for bzlib.h... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
...

**Comment by colinbrislawn** [comment]
It does not look like it's finding it...

```
checking for library containing BZ2_bzRead... -lbz2
checking for library containing gzoffset... no
...
checking bzlib.h usability... yes
checking bzlib.h presence... yes
checking for bzlib.h... yes
checking for gcc... gcc
```

Are my paths right?
```
[vsearch]$ echo $CPATH
/people/asdf/bin/git-repos/zlib/
[vsearch]$ echo $LD_LIBRARY_PATH 
/people/asdf/bin/git-repos/zlib/
```

**Comment by xflouris** [comment]
Hi @colinbrislawn,

I believe the problem is that autoconf finds a version of zlib older 
than 1.2.4  (which lacks gzoffset function) in the system library path.
In case you have compiled/installed a newer zlib in a different path, 
e.g. /people/asdf/bin/git-repos/zlib, then instead of running 
./configure you should run the following:

LIBS=/people/asdf/bin/git-repos/zlib ./configure

Hope this helps,

Tomas

**Comment by torognes** [comment]
Hi @colinbrislawn,

The problem should be fixed now in version 1.4.2, as vsearch will dynamically load the libraries if they are available. The supplied binary is compiled with support for both gzip and bzip2 compressed files, but they are not required. Their availability is checked at runtime.

Also, vsearch no longer requires version 1.2.4 of zlib as I found a simple workaround that makes if work also with older zlib versions.

**Comment by torognes** [comment]
Hi @xflouris 

I found a workaround for the missing gzoffset function in zlib 1.2.3 and earlier. It might be useful for PEAR and other projects as well.

Old code (line 493 in fasta.cc):
```
h->file_position = gzoffset(h->fp_gz);
```

New code (lines 502-507 in fasta.cc):
```
int fd = dup(fileno(h->fp));
h->file_position = lseek(fd, 0, SEEK_CUR);
close(fd);
```

It uses gzdopen to open the gzipped file (h->fp_gz) while keeping the original file (h->fp) open. Instead of using gzoffset on h->fp_gz it will make a duplicate file handle and then use lseek on the new handle to retrieve the position before closing the duplicated handle. Using lseek directly on the original handle wont work (it always returns zero), however duplicating it apparently triggers an update of the current file position.

The approach was suggested here:
http://stackoverflow.com/questions/21090556/how-to-report-progress-of-data-read-on-a-quagzipfile-quazip-library

The performance seems fine.

**Comment by colinbrislawn** [comment]
:clap: @torognes 

```
$ git pull
...
$ ./autogen.sh
...
$ ./configure
...
$ ./make
...
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
```

Thank you!
