### ISSUE TITLE
fulldp option

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [torognes/vsearch#200]
is there any way to turn the `--fulldp` option off?  The manual says always on ... however I don't understand why it's an option if it can't be turned off/on ...

**Comment by torognes** [comment]
No, the `--fulldp` option is always on. The option is there for compatibility with usearch, so that any script made for usearch that uses this option will work as expected if usearch is replaced with vsearch. The `--fulldp` option does not have to be removed from the script, it will just be ignored.
