### ISSUE TITLE
Old versions on conda

### ISSUE THREAD

**Issue by p1nox** [torognes/vsearch#205]
Is there any plan to add older versions on conda?

I know we can find vsearch on https://anaconda.org/biocore/vsearch and https://anaconda.org/bioconda/vsearch, but the older version there is 1.9.2. So is it possible to push versions like 1.6.0 https://github.com/torognes/vsearch/releases/tag/v1.6.0 ?

**Comment by colinbrislawn** [comment]
Hello @p1nox,

I've contributed to the vsearch conda packages, but have not thought to support older versions. Why not just use the newer versions? Are the specific older versions that you would like avaiable through conda?

**Comment by p1nox** [comment]
Yes, right now we are using 1.6.0 version, and we found that if we upgrade to 2.0.0 (which is pushed in bioconda), our end results are different, probably because the process of removal of chimeras is different.

So as we are moving our stack to use conda, it would be great to be able to install vsearch 1.6.0 using it, instead of installing it manually.

**Comment by colinbrislawn** [comment]
So having old versions easily available would help people replicate old results. That makes sense to me. 

Just to be argumentative, would is also make sense to update your results using a newer (or newest!) version of vsearch available? The preprint of the vsearch manuscript came out after v2 as released, and [numerous improvements](https://github.com/torognes/vsearch/releases) have been made since then. Wouldn't it make more sense to update your results, instead of building a bioconda package for old code?

I'll look into the process of building older packages and maintaining them on bioconda. I know it's possible, and this is a good opportunity for me to learn.

**Comment by p1nox** [comment]
The idea is precisely that, to reproduce old results, if we move to a different version we will obtain new results, but we wouldn't be able to replicate the old ones.

**Comment by p1nox** [comment]
Addendum: We want exactly that, to be able to reproduce in any time the same result we have recorded with an old version and with a newer version.

**Comment by colinbrislawn** [comment]
So this is possible, but tricky see
https://github.com/bioconda/bioconda-recipes/issues/232 

The build and test process will also be different for this old version of vsearch. I'll have to look into this later. Until then, a good workaround would be to set up different conda environments, then install different versions of vsearch into each one. It's not as elegant to install, but just as easy to use and to compare results between projects.

**Comment by p1nox** [comment]
Great, thanks for the answer and the effort 😃

**Comment by frederic-mahe** [comment]
Hi guys, it seems that this issue can be closed now. There is not much the vsearch development team can do about that.

**Comment by colinbrislawn** [comment]
This can probably be closed, as development and support is focused on the newest version.

@p1nox , There are older versions of swarm on conda, so this is _possible_ to do with vsearch. Do you still want this or is the workaround I posted good enough?

**Comment by p1nox** [comment]
No problem, we managed to solve to this problem no worries. Thanks for the support 😃  👍
