### ISSUE TITLE
OTU sequence short than before

### ISSUE THREAD

**Issue by zh3ngq1n** [torognes/vsearch#236]
hi,torognes:
       I used this command to do OTU . But I found that one OTU sequence is short than before. Why this happened? Can you help me to solve this problem? Thanks!

vsearch --cluster_size  uniques_sorted.fa --consout cluster.fasta  --id 0.97 --relabel_keep

>Uniq27;size=38;F1.3014:sequence before vesearch
GCAGCCGCCGCGGTAACACCGGCGGCCCGAGTGGTAACCGATTTTATTGGGTTTAAAGGGTCCGTAGCCGGCCTGTTAAG
TCTCTTGGGAAATCTGGCGGCTCAATCGTCAGACGGTCAAGAGATACTGACAGGCTTGGGACCGGTAGAGGTGGGAGGTA
CTCCAGGGGTAGAGGTGAAATTTTGTAATCCTTGGGGGACCATCGATGGCGAAGGCATCCCACTAGAACGGGTCCGACGG
TGAGGGACGAAAGCTGGGGGCACGAACCGGATTAGATACCCGGGTAGTCCCAGCCGTAAACGATGCTCGCTAGGTGTCAG
ATGCGGTGCGACCGCATTTGGTGCCGCAGTGAAAACCTGAAGCGAGCCACCTGGGAAGTACGGTCGCAAGGCTGAAACTT
AAAGGAATTGGCGGGGGA

>centroid=Uniq27;size=38;F1.3014;seqs=801;sequence after vesearch
CCAGCCGCCGCGGTAACACCGGCGGCCCGAGTGGTAACCGATTTTATTGGGTTTAAAGGGTCCGTAGCCGGCCTGTTAAG
TCTCTTGGGAAATCTGGCGGCTCAATCGTCAGACGGTCAAGAGATACTGACAGGCTTGGGACCGGTAGAGGTGGGAGGTA
CTCCAGGGGTAGAGGTGAAATTTTGTAATCCTTGGGGGACCATCGATGGCGAAGGCATCCCACTAGAACGGGTCCGACGG
TGAGGGACGAAAGCTGGGGGCACGAACCGGATTAGATACCCGGGTAGTCCC

**Comment by colinbrislawn** [comment]
Good afternoon,

I think the `--consout` flag is causing this. This flag outputs the 'consensus' of all the hits, representing the section of the reference OTU that all query sequences agreed with. Because these matching queries are up to 3% different, only the 100% matching part of this reference OTU was reported in the `--consout` file.

If you want to see the full length of each OTU, you could use the `--centroids` output instead. I _think_ this is the output you are looking for.

PS. The [vsearch forums](https://groups.google.com/forum/#!forum/vsearch-forum) are a great place to ask questions like this. You could post other questions over there. The issue tracker on github is a better fit for reporting bugs.

**Comment by zh3ngq1n** [comment]
Thank you very much. 
If i have another questions next time,i will go to vsearch forums.
Thanks again.
