### ISSUE TITLE
Lifting memory limitation

### ISSUE THREAD

**Issue by ccedmendoza** [torognes/vsearch#244]
Hi,
I would like to use the clustering tool to cluster sequences from a large database (2 million + sequences) with big sequences (1 million+ bp). The problem is the fact that vsearch limits the memory usage, since it never exceeds 15,2G., and so it takes forever to cluster the database. I was wandering if there was a way to lift this limit?

Thank you for your time.

**Comment by torognes** [comment]
VSEARCH is not designed to handle very long sequences like 1 million+ bp. In fact it does not work well for sequences longer than about 10kbp due to the way it aligns sequences. Aligning millions of such long sequences is outside of the direction that we will develop VSEARCH. I am sorry that I cannot recommend any other tool for this job. If you ask in the VSEARCH Forum at https://groups.google.com/forum/#!forum/vsearch-forum someone may have a suggestion.

**Comment by ccedmendoza** [comment]
Ok, thank you for your help.
