### ISSUE TITLE
compilation warning with GCC 7.1

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#256]
Tested on the new Fedora 26:
```
results.cc: In function 'void results_show_alnout(FILE*, hit*, int, char*, char*, int64_t, char*)':
results.cc:451:33: warning: 'snprintf' output truncated before the last format character [-Wformat-truncation=]
           int qlenlen = snprintf(&dummy, 1, "%" PRId64, qseqlen);
                         ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
results.cc:451:33: note: 'snprintf' output between 2 and 21 bytes into a destination of size 1
results.cc:452:33: warning: 'snprintf' output truncated before the last format character [-Wformat-truncation=]
           int tlenlen = snprintf(&dummy, 1, "%" PRId64, dseqlen);
                         ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
results.cc:452:33: note: 'snprintf' output between 2 and 21 bytes into a destination of size 1
```

**Comment by cometsong** [comment]
I get the same `results.cc` warnings on:
`uname: Linux myhost 2.6.32-573.8.1.el6.x86_64 #1 SMP Tue Nov 10 18:01:38 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`
`/etc/redhat-release:  CentOS release 6.7 (Final)`

Using autoconf/2.69, gcc/7.1.0, bzip2/1.0.6, zlib/1.2.8

Many other errors crapped out and did not successfully compile.   e.g.:
`chimera.cc:(.text+0x29ae): undefined reference to 'log10'` was one of them.

I'm checking on sending specific LDFLAGS/etc to get it going.

**Comment by torognes** [comment]
I have just tried compiling with the following gcc versions: 4.4.7, 4.7.2, 4.8.0, 4.8.2, 4.9.0, 4.9.1, 4.9.2, 5.1.0, 5.2.0, 5.3.0, 6.1.0, 6.3.0, and 7.2.0. Except for version 5.1.0 and 7.2.0 I do not get any warnings or errors.

I get the same warnings as you from GCC 7.2 when I compile it. I get a different warning with gcc 5.1.0. I'll look into them.

I usually use gcc version 4.9.2 for compiling and making the binaries, as it makes code that is dependent on libraries that seem to be present on most systems. Later gcc versions seems to make code dependent on newer libraries that are not available on slightly older systems. 

Regarding the error that @cometsong got with undefined reference to log10, I guess it is due to a missing math library. I do not get this message.

Remember to run ./autogen.sh, ./configure, and make clean before make.

**Comment by torognes** [comment]
A fix has been committed.
