### ISSUE TITLE
Fatal error: No output files specified vsearch v2.6.2_macos_x86_64 

### ISSUE THREAD

**Issue by bioinfonm** [torognes/vsearch#284]
Hello,

 Running this command:
`vsearch -usearch_global Fungal-Mock-A-ITS4mod-assembled-forward.fasta -db Galaxy201-\[VSearch_clustering_on_data_200__Consensus_Sequences\].fasta -strand plus -id 0.97 -threads 6 -uc closedref.97.map.uc --biomout closedred.97.biom --consout closedref-97-ITS-consout.fasta`

will not generate the --consout fasta file.

And running this command:
`vsearch -usearch_global Fungal-Mock-A-ITS4mod-assembled-forward.fasta -db Galaxy201-\[VSearch_clustering_on_data_200__Consensus_Sequences\].fasta -strand plus -id 0.97 -threads 6 --consout closedref-97-ITS-consout.fasta`

generates the following error

```
vsearch v2.6.2_macos_x86_64, 16.0GB RAM, 8 cores
https://github.com/torognes/vsearch



Fatal error: No output files specified
```

I was curious if -usearch_global supports --consout command? I am trying to do a closed-reference OTU picking. 

Thanks!

**Comment by colinbrislawn** [comment]
Good afternoon,

>I was curious if -usearch_global supports --consout command?

It does not, but that's by design! 

Vsearch does both search and clustering. The command `-usearch_global` is for search, and the output shows how your inputs match to your database. A command like `-cluster_fast` is for clustering, and the output shows how reads form clusters, and what is the consensus sequence of each newly made cluster.

It does not make any sense to ask about `--consout` with `-usearch_global`, because `-usearch_global` is not performing clustering and is not making any new OTU centroids. If you want to know what are the OTU centroids when running `-usearch_global` you can just check inside your `-db` file. All the OTU centroids are listed in there.

When the Qiime devs coined the phrase 'closed-ref OTU picking', they were misleading.  During closed-ref "picking", no new OTUs are picked. All the OTUs are already in the database, and you are only searching, not clustering.

Here is how to do closed-ref OTU picking followed by picrust:


```
vsearch -usearch_global seqs.fna \
-db ~/qiime_default_reference/gg_13_8_otus/rep_set/97_otus.fasta \
-strand plus -id 0.97 -uc gg.map.uc -biomout gg_closed_ref.biom

biom add-metadata -i gg_closed_ref.biom -o gg_closed_ref_w_tax.biom \
--observation-metadata-fp ~/qiime_default_reference/gg_13_8_otus/taxonomy/97_otu_taxonomy.txt \
--sc-separated taxonomy --observation-header OTUID,taxonomy

normalize_by_copy_number.py \
-i gg_closed_ref.biom \
-o picrust/normalized_otus.biom

predict_metagenomes.py -i picrust/normalized_otus.biom \
-f -o picrust/ko_metagenome_predictions.tab \
-a picrust/nsti_per_sample.tab

```

Let me know if that helps,
Colin

---

P.S. Are you asking about using --usearch_global for [recentering OTUs](https://www.drive5.com/usearch/manual7/recenter.html)? That's a different use case.
