### ISSUE TITLE
-search_exact and -usearch_global different outputs

### ISSUE THREAD

**Issue by Felipealbornoz** [torognes/vsearch#295]
Hi, I was wondering why using -search_exact gives VERY different results than using -usearch_global with -id 1.0 --iddef 1, when creating an OTU table?

command for -search_exact:
vsearch --search_exact rawseqs.fasta --db OTU.fasta --iddef 1 --strand both --otutabout otu.table.exact.txt

command for -usearch_global:
vsearch --usearch_global rawseqs.fasta --db OTU.fasta --iddef 1 --id 1.0 -strand both --otutabout otu.table.global.txt

**Comment by torognes** [comment]
The command `search_exact` identifies only perfectly identical sequences (same length, same sequence). The `--iddef` option is ignored for `search_exact`. There are no heuristics involved, it always finds just the exact matches.

The command `usearch_global` uses heuristics to try to identify similar sequences by looking at shared k-mers. When using `--iddef 1` and `--id 1.0` it should also just report perfectly identical sequences, however due to the heuristics it may occasionally fail to find the perfect matches. This depends on the k-mer composition of the sequences. Several very similar but not identical sequences might have the same k-mer profile and confuse the search.

The default minimum sequence length (`--minseqlength`) is 32 for `usearch_global` while 1 for `search_exact`, that could also eliminate some matches if some of your sequences are short.

Masking (`--qmask` and `--dbmask`) might also influence the results, as masked k-mers are not used when comparing sequences with `--usearch_global`.

If you turn off masking (`--qmask none --dbmask none`) and set the mininmum length to 1 (`--minseqlength 1`), you might get more similar results.
