### ISSUE TITLE
Add an option to output to stdout?

### ISSUE THREAD

**Issue by ZeweiSong** [torognes/vsearch#317]
I was wondering if it is possible to add an option like -stdout. So that instead of writing the result to a file, redirect it to stdout.

This may come handy when someone wants to implent vsearch into a script.

Thanks!

**Comment by torognes** [comment]
This feature is already available. You simply use a dash (`-`) instead of the filename for the file that you want to write to `stdout`. An example:

`vsearch --fastq_filter input.fastq --quiet --fastaout - | less`

When `stdout` is the console like in the example above, It is often advantageous to also use the option `--quiet` to avoid interruptions with messages written to `stderr`.

Since some commands write output to several files, it is necessary to specify what output you want written to stdout.

The dash (`-`) is a substitute for `stdout` for all output files. It can also be used instead of `stdin` for all input files.

**Comment by frederic-mahe** [comment]
To complete Torbjørn's answer, you can use a dash `-`, or `/dev/stdout`, or a process substitution `>(...)` to redirect vsearch's output, so it can be piped directly into another command. If you feel adventurous you can even use named pipes to redirect multiple output to multiple commands without having to store any intermediate file.

**Comment by ZeweiSong** [comment]
Thanks, it works!
