### ISSUE TITLE
derep_fulllength cluster size does not sum up to the original input

### ISSUE THREAD

**Issue by mys721tx** [torognes/vsearch#324]
### Problem
The sum of all cluster sizes in `all.derep.fasta` is different from that in `all.fasta` when use `vsearch --derep_fulllength`. The documentation does not mention the default behavior when `--maxuniquesize` or `--minuniquesize` is unspecified.

### How to reproduce:
1. Build VSEARCH from 67a88bc.
2. Generate `all.fasta` per the [example pipeline](https://github.com/torognes/vsearch/wiki/VSEARCH-pipeline).
3. Invoke `derep_fulllength`: ```vsearch --derep_fulllength all.fasta  --output all.derep.fasta```
4. Count the sizes in the FASTA file. I used `grep` to extract the FASTA header and then piped them into [following Python script](https://gist.github.com/mys721tx/6c95b460fd3cb6de8c031293ebbc6bf6). The sum of all cluster sizes in `all.fasta` is 124733. The sum in `all.derep.fasta` is 22399.

**Comment by colinbrislawn** [comment]
This is the best issue I've seen all week. 👍 
Thanks for reporting.

**Comment by torognes** [comment]
Thanks for reporting this issue and for describing how to reproduce it.

However, this is expected behaviour of VSEARCH. The reason is that when the `--sizein` and `--sizeout` options are not specified, the sizes (abundances) are ignored and the fasta headers are just copied directly from input to output (from the first sequence in the cluster). When `--sizein` and `--sizeout` is specified the sizes will be taken into account and added together. In the example pipeline these options are included. If you add `--sizein --sizeout` to your command you will get the expected results.

Perhaps the default behaviour should have been to take abundances into account, but its made this way for compatibility with usearch.

When the `--minuniquesize` and `--maxuniquesize` options are not specified, all clusters will be output no matter the size.

**Comment by frederic-mahe** [comment]
Since `--sizein` and `--sizeout` are often necessary, maybe the manpage should be modified to mention them in the definition of the `--derep_fulllength` command? Maybe [like so](https://github.com/torognes/vsearch/commit/526d2d510392fdbfadb3938785d3ecc316004b35)?

**Comment by mys721tx** [comment]
Solved in 526d2d5. Thanks @frederic-mahe !
