### ISSUE TITLE
--fastq_mergepairs produces q-scores of 40

### ISSUE THREAD

**Issue by colinbrislawn** [torognes/vsearch#326]
A qiime 2 user [reported](https://forum.qiime2.org/t/losing-almost-all-reads-after-running-deblur-on-paired-end-sequences/5479/5) that merging reads produces consensually high q-scores in the area of overlap. Graph of q-scores after merging:
<img width="638" alt="screen shot 2018-08-12 at 2 53 45 pm" src="https://user-images.githubusercontent.com/10355152/44006855-f4fa3824-9e3f-11e8-8464-18ebdfc497f8.png">

Is this expected behavior? Does this indicate an issue with vsearch of with their input reads?

Thanks!

**Comment by torognes** [comment]
This seems reasonable. In the overlap region the q-scores will increase considerably due to the increased certainty of the base call from two reads. The scores are calculated as in USEARCH and described in Edgar & Flyvbjerg (2015) [doi:10.1093/bioinformatics/ btv401](https://doi.org/10.1093/bioinformatics/ btv401). Due to the default value of 41 for the `--fastq_qmax` option, the q-scores are clipped at 41, otherwise they would be even higher. The `--fastq_qmax` option argument may be increased to 93 to see the full range. The default is set to 41 for compatibility with USEARCH and with other software that may not expect higher values.

**Comment by chaibenl** [comment]
For convenience, I chose to run "vsearch --fastq_mergepairs" prior to dada2 (in Qiime 2), instead of merging the paired reads within dada2. In you opinion, could arbitrary q scores in the overlap regions potentially confuse dada2 in ASV generation? Thank you.

**Comment by colinbrislawn** [comment]
> potentially confuse dada2

Dada2 should be able to process these reads as if they were from single end sequencing... but you would be missing out of the part of the dada2 algorithm that estimates error rates looking for consistency in the area of overlap.

I think your method should work, but if you are going to omit a key part of the dada2 method, why use it at all?

**Comment by chaibenl** [comment]
Thank you for your insights, Colin!

Benli
