### ISSUE TITLE
--cluster_fast is stuck at clustering step for over 5 days

### ISSUE THREAD

**Issue by Zoites** [torognes/vsearch#331]
I'm running vsearch using the following command: 
`vsearch --cluster_fast  file.fasta --id 0.97 --query_cov 1.0 --target_cov 1.0 --maxgaps 1 --iddef 4  --leftjust --rightjust  --centroid file.vsearch.fasta --threads 10"`

Here is progress from stdout:
vsearch_ v2.8.0_linux_x86_64, 504.9GB RAM, 20 cores
https://github.com/torognes/vsearch

Reading file file.fasta 100%
6997097200 nt in 69970972 seqs, min 100, max 100, avg 100
Masking 100%
Sorting by length 100%
Counting k-mers 100%
Clustering

Any tips on what is going on? How can I speed up the clustering?
The input file has over 69 million sequences with 100 nucleotide lengths.

**Comment by torognes** [comment]
My first thought is that this dataset is simply too big for this algorithm to handle in reasonable time. It may take months.

I assume you have dereplicated it first, otherwise you should do that.

You may try Swarm :-)

**Comment by colinbrislawn** [comment]
+1 dereplication (but you have probably done that already).

These settings jumped out to me: 
`--query_cov 1.0 --target_cov 1.0 --maxgaps 1 --iddef 4 --leftjust --rightjust`

I notice that you are trying very hard to make sure there is only one gap, by rejecting alignments that start or end with gaps and also alignment that have >1 gap in the middle. Sequencing amplicons often have a few base pairs hanging off at the ends, so exact 100% overlap is always expected after dereplication.

If I may ask, why are you trying to avoid gaps? 🤔 

---


`--query_cov 1.0 --target_cov 1.0`
I think these settings are important when using --usearch_global to align short queries to longer targets in the database (say V4 16S against full length 16S). Given that all your reads are 100bp long, I worry that the specific scoring of these two parameters are throwing out reads that are 99/100 bp overlapping.


---

What happens if you use all default settings?

```
vsearch --cluster_fast file.fasta --id 0.97 --iddef 4 --centroid file.vsearch.fasta --threads 10
```

**Comment by Zoites** [comment]
Thanks for the suggestions. I figured out a way to reduce the number of input sequences to vsearch.
