### ISSUE TITLE
sample IDs containing a - are collapsed for OTU table

### ISSUE THREAD

**Issue by Shellfishgene** [torognes/vsearch#335]
Hi!
I have samples named `1-1234, 1-1235, 2-1234` and so on. Going through the 16S pipeline this yields sequence names such as `1-1234.1;size=5` in `the all.nonchimeras.fasta` file. However the last clustering step that generates the OTU tables reduces the samples to just the part in front of the dash, so for this example I would only get the rows `1` and `2` in the table.
I'm not sure if this a bug or a feature, I could not find anything about it in the docs, maybe I missed it.

**Comment by colinbrislawn** [comment]
Hello,

I'm not sure where the characters allowed in sample names are listed. As you have discovered, dashes`-` are not allowed in sample names because only the prefix is used during clustering. I think this line of documentation is closest:
>The sample identifier may contain any printable character except semicolons. If no such sample label is found, the identifier in the initial part of the header will be used, but only letters, digits and underscores are allowed.

So replace the `-` in your sample name with an underscore`_` and this should work fine. `1_1234` 👍

**Comment by Shellfishgene** [comment]
They were underscores before but those don't work with usearch ;). Thanks!
