### ISSUE TITLE
does `derep_fullllength` support multithreading?

### ISSUE THREAD

**Issue by devonorourke** [torognes/vsearch#357]
Good morning,
I was looking through the manual to try and determine if the `derep_fulllength` command supported multithreading or not. Some parts of the manual indicate when this _is not_ supported, and others show when it is allowed, but in this instance I couldn't determine the situation. An old closed [post](https://github.com/torognes/vsearch/issues/90) made me think it is possible, so perhaps I'm just missing the clearly documented parameter staring me in the face (this happens far too often). 
Thanks for your help,
Devon

**Comment by torognes** [comment]
None of the dereplication commands (`derep_fulllength` or `derep_prefix`) support multithreading. I will make this clear in the manual.

**Comment by devonorourke** [comment]
Thanks very much @torognes,
I'm sure there's a good reason why it's not multithreaded given that so many other applications within `vsearch` support that kind of data processing. I was just curious if you cared to expand on why this particular function isn't. Is it something that's just not high up a 'to-do' list, but is possible?, or is it something about the nature of the function that doesn't allow it?
In any event, it's no problem at all - everything in `vsearch` is plenty fast for my needs already!
Thanks

**Comment by mys721tx** [comment]
1. We need to go through every FASTX records in order to identify replications and FASTX file is linear by nature.  I don't know if there is any effective way to start a new thread in the middle of the file and just start reading.
2. Data race will cause problem when multiple threads are writing to the hash table. Lock/mutux are needed to make sure that only one thread can write to a particular hash table entry at any given time. Locks can take a toll on performance.

The second problem may be solved by having thread-local hash table that are merged after all threads completed their jobs. However, due to the first problem, there is no easy way to run this in multiple threads.

**Comment by devonorourke** [comment]
Very cool - thanks for the great explanation!

**Comment by torognes** [comment]
Dereplication is already pretty fast even with large datasets. Multithreading appears somewhat complicated, so I am not sure how much there is to gain. Therefore it is not high up on the priority list.
