### ISSUE TITLE
fastx_revcomp: relabel strips abundance annotations

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#391]
command `--fastx_revcomp` preserves abundance annotations:
```sh
printf ">s;size=1;\nA\n" | \
    vsearch --fastx_revcomp - --fastaout - --quiet
```
```
>s;size=1;
T
```
but adding a `relabel` options strips abundance annotations:
```sh
printf ">s;size=1;\nA\n" | \
    vsearch --fastx_revcomp - --fastaout - --quiet --relabel_sha1
```
```
>c2c53d66948214258a26ca9ca845d7ac0c17f8e7
T
```
even when using the `--sizein --sizeout` options:
```sh
printf ">s;size=1;\nA\n" | \
    vsearch --fastx_revcomp - --fastaout - --quiet --relabel_sha1 --sizein --sizeout
```
```
>c2c53d66948214258a26ca9ca845d7ac0c17f8e7
T
```
For future reference, valid options for the fastx_revcomp command are: --bzip2_decompress --fasta_width --fastaout --fastq_ascii --fastq_qmax --fastq_qmin --fastqout --gzip_decompress --label_suffix --log --no_progress --notrunclabels --quiet --relabel --relabel_keep --relabel_md5 --relabel_self --relabel_sha1 --sizein --sizeout --threads --xee --xsize

**Comment by torognes** [comment]
Fixed in 6b32b5b618d9c0d860712b6b51ff6ace69ef6761. It will now add the abundance when using `fastx_revcomp` using both `relabel` and `sizeout`. When only `relabel` is specified, no label will be included. This is in line with similar commands like `fastx_filter` and `fastx_subsample`. 

The modification has been made for `fastq_convert` as well.
