### ISSUE TITLE
--allpairs_global problem with identity calculation

### ISSUE THREAD

**Issue by gregdenay** [torognes/vsearch#424]
Hi, I'm trying to use the --allpairs_global option to get pairwise global (end to end) alignment of my sequences. 
However it seems that the calculated ID is based only on the local alignment and not on the full sequences, although I am using the `--iddef 3` option that should calculate the identity based on the longest sequence length.

Is this the expected behaviour and is there a way to report the percent identity from the full length sequences, or even force alignment on the full length sequences? I could only find the --mincols option, which wouldn't work for variable-length sequences.

Here is the command I ran (Version 2.14.2):
```
vsearch --allpairs_global tests/fasta/sequences_trim.fa \
                --iddef 3 \
                --minqt 1 \
                --threads 8 \
                --id 0.9 \
                --userout tests/pairwise_alignment/table.tsv \
                --userfields query+target+id+mism+gaps+alnlen+qlo+qhi+ql+tlo+thi+tl \
                --alnout tests/pairwise_alignment/alignments.txt 
```

Here is an output example:
```
query	target	id	mismatch	gaps	aln_length	qstart	qend	qlength	tstart	tend	tlength
NC_015087.1	NC_039921.1	96.2	1	0	10	1	79	79	1	74	74
NC_015087.1	NC_014698.1	96.2	1	0	10	1	79	79	1	70	70
```

The alignments look like this:
```
 Query 79nt >NC_015087.1
Target 74nt >NC_039921.1

Qry  1 + TTAAAAATTC 10
         |||||| |||
Tgt 65 + TTAAAATTTC 74

10 cols, 9 ids (96.2%), 0 gaps (0.0%)

 Query 79nt >NC_015087.1
Target 70nt >NC_014698.1

Qry  1 + TTAAAAATTC 10
         |||||| |||
Tgt 61 + TTAAAATTTC 70

10 cols, 9 ids (96.2%), 0 gaps (0.0%)
```

**Comment by torognes** [comment]
This is expected behaviour. It may look a bit unexpected though. Part of the reason is that although the alignments are actually global alignments, the terminal gaps are not shown, and sometimes not counted. These terminal gaps may be very long. There are two things I think will help:

1) By default vsearch uses very small terminal gap penalties. The ordinary gap open and extension penalties are 20 and 2, respectively. However, the terminal gap open and extension penalties are just 2 and 1, respectively. Since the terminal gap penalties are so small, the alignments will sometimes look like semi-global alignments, like the ones in your example where it is just the opposite ends of the sequences that seems aligned. To use ordinary gap penalties all over you could use these options: `--gapopen 20 --gapext 2`. The alignments will then look more like ordinary optimal global alignments. Please see the manual for details. This gap penalty scheme is similar to usearch.

2) If you want to take terminal gap penalties into account when computing the identity between sequences you should rather use `--iddef 0`, `--iddef 1` or `--iddef 4` (the latter two are equivalent). The options `--iddef 2` and `--iddef 3` will ignore or greatly reduce the effect of terminal gaps.

I hope this clarifies the issue.

**Comment by gregdenay** [comment]
Thanks a lot. Introducing the above changes give the expected output.
