### ISSUE TITLE
is test suite in sync with vsearch ?

### ISSUE THREAD

**Issue by EricDeveaud** [torognes/vsearch#442]
Hello 

is the vsearch-test repo https://github.com/frederic-mahe/vsearch-tests in sync with vsearch repo ?
I just do a fresh installation of vsearch 2.17.0 from tag archive, 
clonned the vsearch-test commit https://github.com/frederic-mahe/vsearch-tests/commit/ee8f3627ca31ba0bf28faa1876a9118390d6e6c5
and ran the test suite as described: `bash run_all_tests.sh`

and got a lot of failure 

attached the output 
[log.txt](https://github.com/torognes/vsearch/files/6337695/log.txt)

**Comment by frederic-mahe** [comment]
hi @EricDeveaud 

`swarm-tests` is nearly-complete and in sync with `swarm`, but `vsearch-tests` has not yet reach the same coverage level for `vsearch`. A couple days ago, I've started to clean up some of the existing tests as many are broken or miss their target entirely. Fixing that should take several weeks. Once that will be done, I think the most rewarding approach will be to write tests for all reported issues (about 440 issues so far). That should help prevent regressions and improve code coverage.

**Comment by EricDeveaud** [comment]
thanks for the comment and update.
I know providing an in-sync test suite require an tremendous work.

**Comment by frederic-mahe** [comment]
The `vsearch` test suite is being refactored from scratch. From now on, `bash run_all_tests.sh` will only run reviewed and valid tests.

I've reviewed and validated about 50 tests this week, and I plan to do the same next week (there are currently 1,519 tests to review).

Technically, even though it has a low coverage, we can consider that the test suite is in sync with vsearch. That's why I am going to close that issue.

**Comment by EricDeveaud** [comment]
merci Fréderic !!!
