### ISSUE TITLE
closed_ref workflow as usearch -closed_ref

### ISSUE THREAD

**Issue by jianshu93** [torognes/vsearch#443]
Dear vsearch team,

Though close reference is not recommended anymore but it is useful for extracted short 16S from Metagenome (randomly sequences short fragments from bacterial genome/full 16S region) if we want to have a quick look of the overall community composition. I understand the search-global option is semi-global alignment and it works for short 16S fragements. my question is how to count the number of each fragements that mapped to the same database sequences? search-global can give blast format output and then I need to look through that table to have abundances of each closed picked OTUs right? Any script to do that quickly? the usearch -closed_ref can do that directory and output the OTU table. Any possibility that vseach also include this? I hate qiime2 even though it does the step I was talking about. Using qiime2 is a waste of time. 

Thanks,

Jianshu

**Comment by colinbrislawn** [comment]
Hello Jianshu,

I'm not part of the vsearch dev team, but yes, I think you can do something like this using vsearch.

`vsearch --usearch_global sample1.fna --db SILVA_SSURef_NR99.fasta --id 0.95 --blast6out sample1.blast6`

The normal issues with closed-ref still apply: this is extremely biased on the database, there will be lots of ambiguous mappings, and taxonomic resolution is not uniform.

"abundances of each closed picked OTUs right?"
I'm not sure that's possible because most reads will map to multiple items in the database, and by default `usearch_global` returns only the top hit, even if the 2nd and 3rd hits are also 100% matches to the database. It might worth a 'quick look,' but this method is far from perfect.

**Comment by jianshu93** [comment]
we can search the entire database and the only keep the unique query ids by selecting the highest identity. then summarize for each sample（the query fasta file is named samplename_seqid

________________________________

**Comment by colinbrislawn** [comment]
>only keep the unique query ids by selecting the highest identity

What if a query sequence aligns to several database sequences all with 100% coverage and 100% identity?

**Comment by jianshu93** [comment]
it does not matter we just choose one. the assignment could be wrong in those cases because they are short. usearch -closed_ref must have considered this situation.

thanks

jianshu

**Comment by jianshu93** [comment]
i think even for amplicon you still have this question when you do close reference but for metagenomic extracted short，nonoverlap fragments we do not have other choices. 

Jianshu
