### ISSUE TITLE
Multithreading support on fastq_filter command

### ISSUE THREAD

**Issue by ZeweiSong** [torognes/vsearch#466]
Hi,

Is it possible to enable multithreading on fastq_filter and fastx_filter? Seems like an easy tweak.

Thanks!

Zewei

**Comment by torognes** [comment]
Thanks for the suggestion. However, I think it is not easy to speed up these functions. The processing of the sequences is relatively quick compared to the time it takes to read and write the input and output files. In order to speed up these operations, one would need to parallelise the reading and writing of FASTA/FASTQ files. That is possible, but not trivial. Also, depending on the file system, there might not be much to gain if the operating system is unable to read or write the files faster, even with multiple threads.  All things considered, I have so far concluded that it is probably not worth the effort. If you have other opinions on this I would be happy to discuss.
