### ISSUE TITLE
optimization flag is set to -O2

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#480]
hello @torognes and @xflouris I've just noticed that the compilation optimization flag for `vsearch` is set to `-O2` during configuration (visible when running the `make` command).

I can't remember why and when that particular level of optimization has been selected, so I report it in case it went unnoticed so far.

**Comment by torognes** [comment]
I think `-O2` is a default.

Previously `-O3` was in `configure.ac`, but I moved those optimization flags out of the `configure.ac` file with commit d007e76124184d6c95d75cf3567659f0fa9e83ec a while ago, because it seems like it is not the recommended way to do it.

In the `README.md` it is stated that `-O3` is recommended. This is also used in the `Dockerfile`.

Anyway, I do not think there is any substantial difference between `-O2` and `-O3` for vsearch.

**Comment by frederic-mahe** [comment]
Nothing to change then, thanks!
