### ISSUE TITLE
--uchime_ref segmentaiton fault in 2.29.0

### ISSUE THREAD

**Issue by labrat789** [torognes/vsearch#577]
Hi, 

I've installed vsearch 2.29.0 on our debian based grid, and during testing I've had issues with --uchime_ref, as I get a segmentation fault when calling the command on my sequences. This does not happen in version 2.22.1. I've uploaded a zipped archive with the stdout as well as the input files. Any help is much appreciated.

Best,
chris

[Archive.zip](https://github.com/user-attachments/files/17494421/Archive.zip)

**Comment by frederic-mahe** [comment]
This is the first bad commit: https://github.com/torognes/vsearch/commit/4d062bf80f2fa1e22bc2b959b51085a88adabd26

**Comment by frederic-mahe** [comment]
bug fixed in https://github.com/torognes/vsearch/commit/dfcc6bdcbdb2ccddfac4cc9a1070d1f72d91d21b (dev branch)

@labrat789 I am the one who introduced that bug, sorry about that. Thank you for reporting it and for providing a reproducible example. I'll update our test-suite with a similar example to prevent future errors such as this one.

**Comment by torognes** [comment]
Good that you found the problem so quickly.

I'll very soon release a new version (2.29.1) with this fix.

**Comment by labrat789** [comment]
Hi, many thanks for getting to this so soon. I've been using this software for some time, I've always appreciated the work you guys do. I'll install the new version on our grid once it's available.

Chris

**Comment by torognes** [comment]
Thanks!

The new version 2.29.1 was just released: https://github.com/torognes/vsearch/releases/tag/v2.29.1
