### ISSUE TITLE
Inconsistent results when using --blast6out or --uc in --usearch_global

### ISSUE THREAD

**Issue by billzt** [torognes/vsearch#580]
Query is `test.fa`, including one sequence.
DB is `testdb.fa`, including three sequences.
version is `v2.28.1_linux_x86_64`

Command is `vsearch --usearch_global test.fa --db testdb.fa --id 0.97 --top_hits_only --strand both --maxaccepts 0 --uc test.out.uc --blast6out test.out.blast`

In `test.out.blast`, there are three hits.
In `test.out.uc`, there is only one hit.

[Archive.zip](https://github.com/user-attachments/files/17794847/Archive.zip)

**Comment by frederic-mahe** [comment]
thanks for reporting that @billzt

If I understand correctly the issue here. You were expecting three hits in the `--uc` output. By default `--uc` only reports the top hit for each query. You need to add the option `--uc_allhits` to see all the hits.

I'll try to improve vsearch's current documentation to make that aspect of `--uc` more obvious. We are also working on a solution to make the vsearch documentation less intricate, more detailed, and easier to navigate (see #269). Please bear with us!

**Comment by billzt** [comment]
Thank you!

**Comment by frederic-mahe** [comment]
- improved documentation for `--uc` and `--uc_allhits` (see https://github.com/torognes/vsearch/commit/9794e6dc874a5b5bc068902168dcf20a458c3cdb)
- tests added to our test-suite: https://github.com/frederic-mahe/vsearch-tests/commit/1ba0cf7ba02d52617e802deae635602bb090995b
