### ISSUE TITLE
Chimera search with translated protein sequences?

### ISSUE THREAD

**Issue by jooolia** [torognes/vsearch#87]
Would it be possible to add an option for using the chimera search with protein sequences? Even if you could turn off the validation of sequences somehow that would allow you to not have characters stripped? 

Tested it out and got this output: 
```466 nt in 7 seqs, min 62, max 69, avg 67
Warning: invalid characters stripped from sequence: E(55) F(24) I(29) L(69) P(30) Q(27)```

So then, even though there were no chimeras found, the sequences are then unusable.

**Comment by colinbrislawn** [comment]
Currently vsearch does not support anything involving protein / amino acid sequences.
See torognes/vsearch#42

I'm also curious in what context would you search a protein for chimeras. I have not heard of that before and am interested in learning more.

**Comment by jooolia** [comment]
Ok! Yes sorry I looked too quickly at the issues. 

I've been using it when I have a protein database used for a reference and when the sequences code for proteins. Data is more reduced at this point too, so was also an attempt to be efficient.

**Comment by colinbrislawn** [comment]
Ah ok...

I understand that protein search would be really useful.
Protein clustering could be cool as well for data set reduction / summarization. 

However, I think that chimera checking is only relevant for DNA sequences...

In a study using the 18S or 16S rRNA gene, PCR primers are used to target that specific region and amplify it (leading to the name amplicon). But PCR is not perfect; during the process of amplification, the polymerase can detach from one molecule and attach to another, leading to a amplicon which is actually part of two different species. The resulting, 'frankenstein' amplicon is a combination of two different microbes and so is called a [chimera](https://en.wikipedia.org/wiki/Chimera_%28mythology%29). So chimea checking is a software solution to a biochemical problem with PCR. 

In a genetic study _without_ PCR amplification, chimera checking is not used because no PCR == no chimeras. (Correct me if I am wrong!) 

PCR is not part of proteomics. So... What biochemical situation would lead to a protein sequence which is really part of two different real proteins? There could be one, most of my experience is with genetics not proteomics.

**Comment by torognes** [comment]
Thank you for the suggestion, but, sorry, support for chimeras in amino acid sequences will not be prioritised.
